# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HrZkhQrbzydoyFhgMydUIZGQ8fAIxCX
"""

def fibonacci(n):
    if n <= 0:
        return []
    elif n == 1:
        return [0]
    elif n == 2:
        return [0, 1]

    fib_seq = [0, 1]
    for i in range(2, n):
        fib_seq.append(fib_seq[-1] + fib_seq[-2])

    return fib_seq
n = 10
fib_numbers = fibonacci(n)
fib_numbers

